/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrowLeft: typeof import('./src/components/icons/ArrowLeft.vue')['default']
    ArrowRight: typeof import('./src/components/icons/ArrowRight.vue')['default']
    Dashboard: typeof import('./src/components/icons/Dashboard.vue')['default']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Graph: typeof import('./src/components/Occupants/Graph.vue')['default']
    Header: typeof import('./src/components/Partials/Header.vue')['default']
    House: typeof import('./src/components/icons/House.vue')['default']
    List: typeof import('./src/components/Occupants/List.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/Partials/SideBar.vue')['default']
  }
}
