version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - '5173:5173'
    networks:
      - common

networks:
  common:
